# Generated by Django 5.0.6 on 2024-05-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_category_product_sub_catgeory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_catgeory',
            new_name='sub_category',
        ),
    ]
